### ISSUE TITLE
The votes on destroyed validator cannot be removed

### ISSUE THREAD

**Issue by banishee** [okex/okchain#169]
## Summary of Bug

1. I have been running a test net
2. then I sent the transaction of destroy-validator
3. after that, I used test accounts to vote for other unjailed validators, in order to make the delegate share on that destroyed validator into zero
4. however, even after re-voting, the delegate share on that destroyed validator was still not changed
5. There is two wired phenomena, as follows:
* one of the delegate share on that destroyed validator is negative
```json
{
    "operator_address": "okchainvaloper1qy4e490rwctehf2xvvjqsmhn4cp4fmyepadax6",
    "consensus_pubkey": {
      "type": "tendermint/PubKeyEd25519",
      "value": "4uJ5dFu8ylSVHhwTQVKa/Wdm1qdQT4tYdAYpW2HyxaE="
    },
    "jailed": true,
    "status": 0,
    "delegator_shares": "-193482.47434760",
    "description": {
      "moniker": "21",
      "identity": "",
      "website": "",
      "details": "Time now: 2020-05-26 11:52:48.519440652 +0800 CST m=+14.042119896"
    },
    "unbonding_height": "300809",
    "unbonding_time": "2020-05-25T17:22:20.289096146Z",
    "min_self_delegation": "0.00000000"
  },
```
* using the command `okchaincli query staking votes-to` to query the vote information, it outputted a long list of voting information, but contained a lot of redundant voting information from the same address, which happened on all the destroyed validator.
```
[
…… 
{
    "voter_address": "okchain1lushklzcfd62wschhs3j3mwlwc0nn6vghtfhe8",
    "votes": "155941.09872791"
  },
…… 
……
……
  {
    "voter_address": "okchain1lushklzcfd62wschhs3j3mwlwc0nn6vghtfhe8",
    "votes": "155941.09872791"
  }
…… 
]
]
```
## Version

v0.10.5

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RevelationOfTuring** [comment]
Thanks for your carefulness！

There was a bug with delegator's rebinding(#133) leading to the inflation of proxy tokens on proxy. It is possible to make a mess if you still keep your block data after the update to v0.10.5.

We will focus on this problem and recommend to clear the data and have a new start with okchain v0.10.5. 

Sincerely @banishee
