### ISSUE TITLE
In InitGenesis, the disordered and intermittent order will generate an error orderNum

### ISSUE THREAD

**Issue by ylsGit** [okex/okchain#242]
## Summary of Bug

The InitGenesis of the order module is as follows
```
func InitGenesis(ctx sdk.Context, keeper keeper.Keeper, data GenesisState) {
	...
	// reset open order& depth book
	for _, order := range data.OpenOrders {
		height := types.GetBlockHeightFromOrderID(order.OrderID)
		...
		orderNum := keeper.GetBlockOrderNum(ctx, height)
		keeper.SetBlockOrderNum(ctx, height, orderNum+1)
		keeper.SetOrder(ctx, order.OrderID, order)
		...
	}
	...
}
```
Here, orderNum represents the number of orders, but not the maximum value of orderID.
For example, there are three orders in `data.OpenOrders`, `ID0005-5` `ID0005-3` `ID0005-8`. Then, `orderNum` is 3, not 8.

When we range the order according to block height, there will be some orders missing.
```
orderNum := k.GetBlockOrderNum(ctx, expiredBlockHeight)
var index int64
for ; index < orderNum; index++ {
	orderID := types.FormatOrderID(expiredBlockHeight, index+1)
	order := k.GetOrder(ctx, orderID)
	...
}
```
As shown in the above code, we will get `ID0005-3`, but no `ID0005-5` `ID0005-8`.

## Expected Result

In the above example, we expect `orderNum` is 8.

## Version

v0.10.8

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zhongqiuwood** [comment]
Please fix this in v0.11 only
