### ISSUE TITLE
x/dex: the initial price of token pair could be negative

### ISSUE THREAD

**Issue by ilovers** [okex/okchain#247]
### 1. Describe

There is no initial price verification when list a token pair. The initial price  of token pair could be negative, which results in the latest price of order could be negative too.

### 2. Impact

No serious impact on the system, but negative price is unreasonable.

### 3. Recover

When the token pair trades, the latest price of order will automatically return to normal based on the market price transaction result. 

## Expected Result
Add initial price verification when list a token pair, the initial price of token pair and the latest price of order should always be positive.

## Version
All latest version, include: master, v0.10.xx

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zhongqiuwood** [comment]
will fix this in 0.11 only
