### ISSUE TITLE
The Products query interface does not verify that the Address is null

### ISSUE THREAD

**Issue by tianxiataiping** [okex/okchain#261]
## Steps to Reproduce

command input:

```
http://192.168.80.118:20259/okchain/v1/products?address=


```

return message ：all the prodocuts on chain

```

```
the expected result: retun []

```

```

## Version

v0.11.0

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ilovers** [comment]
Adress param is not required, so "address=" means address is empty.

**Comment by ilovers** [comment]
This is not a problem. Close it now.
