### ISSUE TITLE
The operator fees query interface cannot return information normally

### ISSUE THREAD

**Issue by tianxiataiping** [okex/okchain#262]
## Steps to Reproduce

command input:

```
http://192.168.80.118:20259/okchain/v1/dex/fees?address=okchain124dlxrznvw28tzd4zsd7epyapk2uhc0tl7v50n

```

return message ：
```
{"code":-1,"msg":"","detail_msg":"Backend Plugin's Not Enabled","data":null}
```
the expected result: 

```

```

## Version

v0.11.0

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ylsGit** [comment]
need to enable backend

**Comment by hufengvia** [comment]
> enable backend

how to enable backend?
