### ISSUE TITLE
okchaincli panic caused by tx multi-send of token module

### ISSUE THREAD

**Issue by tianxiataiping** [okex/okchain#63]
## Summary of Bug

command input:

```
$ okchaincli tx token multi-send --from captain --transfers '[{"to":"okchain1mc6syewprrepkrqn8lzzz2t g6f6tvccu93dn62","amount":"0.02591okt"}]' -b block -y --fees 0.002
```

panic:

```
panic: invalid decimal coin expression: 0.02
```

## Version
v0.10.0

## Steps to Reproduce

command input:

```
$ okchaincli tx token multi-send --from captain --transfers '[{"to":"okchain1mc6syewprrepkrqn8lzzz2t g6f6tvccu93dn62","amount":"0.02591okt"}]' -b block -y --fees 0.002
```
(pic is not required)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RevelationOfTuring** [comment]
Invalid fees params input caused okchaincli panic. The code under the cosmos-sdk's path `x/auth/types/txbuilder.go line 131`  is not recommended to modify. 
@tianxiataiping

**Comment by zhongqiuwood** [comment]
we do not fix P3 & cosmos issue
