### ISSUE TITLE
Error caused by query gov proposals of gov module

### ISSUE THREAD

**Issue by tianxiataiping** [okex/okchain#65]
## Summary of Bug

command input:
```
$ okchaincli query gov proposals
```
Error:
```
ERROR: No matching proposals found
```
## Version
v0.10.0

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zhongqiuwood** [comment]
we do not fix P3 & cosmos issue
