### ISSUE TITLE
base_fee's amount shows not correct of token moudle's params

### ISSUE THREAD

**Issue by tianxiataiping** [okex/okchain#77]
## Summary of Bug
when I query the params of token moudule,base_fee shows 0.0125okt,but in factly the system fee is not fixed 

## Steps to Reproduce

command input:

```
1、$ okchaincli query token params -o json --chain-id okchain --node tcp://192.168.80.98:20157
```

result:

```
{
	'base_fee': {
		'denom': 'okt',
		'amount': '0.01250000'
	},
	'issue_fee': {
		'denom': 'okt',
		'amount': '20000.00000000'
	},
	'mint_fee': {
		'denom': 'okt',
		'amount': '2000.00000000'
	},
	'burn_fee': {
		'denom': 'okt',
		'amount': '10.00000000'
	},
	'modify_fee': {
		'denom': 'okt',
		'amount': '0.00000000'
	},
	'send_fee': {
		'denom': 'okt',
		'amount': '0.00000000'
	},
	'multi_send_fee': {
		'denom': 'okt',
		'amount': '0.01000000'
	},
	'transfer_ownership_fee': {
		'denom': 'okt',
		'amount': '10.00000000'
	}
}

```

## Version
v0.10.0

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RevelationOfTuring** [comment]
In my opinion, `base_fee` should be remove from the token params. But there are some references to it in other modules, just like `backend`.
It's impossible to clear it before the modification in other related module.

Please check: #80 @ilovers @fpChan @tianxiataiping
