### ISSUE TITLE
order's prompt message is redundant,not very friendly for users

### ISSUE THREAD

**Issue by tianxiataiping** [okex/okchain#89]
## Summary of Bug

I sell acoin-232 when I don't have enough balance of this token,the prompt message return all kinds of my tokens. That's not very friendly for users

## Steps to Reproduce

command input:

```
1、$ okchaincli tx order new --product acoin-232_okt -s SELL -p 99  -q 1  --from v101 --fees 0.002okt -y -b block -o json --chain-id okchain --node tcp://192.168.80.98:20157


```
result:

```
{'height': '0', 'txhash': 'FA34C8F6543E86B145ACA1D336B16B24205A58382D558A7DBD6599199E63AA30', 'code': 10, 'raw_log': 'ERROR:\nCodespace: sdk\nCode: 10\nMessage: "insufficient account funds; 0.94100000acoin-232,1.99800000bcoin-f1e,998845.22345400okt is less than 1.00000000acoin-232"\n', 'gas_used': '13532'}

```

## Version
v0.10.0

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RevelationOfTuring** [comment]
### Description
The prompt is caused by the check of money deduction. The `BaseSendKeeper` will return error with the negative rest of money in `x/bank/internal/keeper/keeper.go`  (line 288) under the cosmos-sdk. 

It's not recommend to modify the underlying code in cosmos-sdk.

@tianxiataiping

**Comment by zhongqiuwood** [comment]
we do not fix P3 & cosmos issue
