### ISSUE TITLE
the return message without decoding when query distr's params  Output format default

### ISSUE THREAD

**Issue by tianxiataiping** [okex/okchain#93]
## Steps to Reproduce

command input:

```
1、okchaincli query distr params

```
result:

```
communitytax:
- 34
- 48
- 46
- 48
- 48
- 48
- 48
- 48
- 48
- 48
- 48
- 34
withdrawaddrenabled:
- 116
- 114
- 117
- 101

```

## Version

v0.10.0

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tianxiataiping** [comment]
The problem remains with version v0.10.1

**Comment by RevelationOfTuring** [comment]
It works on v0.10.2. Please check it later.
